"""empty message

Revision ID: 5719cea2ec73
Revises: 6c2364441efe
Create Date: 2024-09-06 12:02:01.003747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5719cea2ec73'
down_revision = '6c2364441efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('playlist_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_name', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
