"""bannedAlbums

Revision ID: 899c7561de33
Revises: db044f98bd81
Create Date: 2024-09-11 10:29:58.824032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '899c7561de33'
down_revision = 'db044f98bd81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banned_albums', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('banned_albums')

    # ### end Alembic commands ###
