"""empty message

Revision ID: bacb3ee53ad2
Revises: c279366b46bb
Create Date: 2024-09-09 11:01:27.840820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bacb3ee53ad2'
down_revision = 'c279366b46bb'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        # Use a CASE statement to handle invalid JSON
        batch_op.execute("""
            ALTER TABLE jobs 
            ALTER COLUMN exceptions_to_banned_genres 
            TYPE JSON 
            USING CASE 
                WHEN exceptions_to_banned_genres IS NULL OR exceptions_to_banned_genres !~ '^\[.*\]$' 
                THEN '[]'::json 
                ELSE exceptions_to_banned_genres::json 
            END;
        """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        # Revert the change, converting back to VARCHAR if needed
        batch_op.execute("""
            ALTER TABLE jobs 
            ALTER COLUMN exceptions_to_banned_genres 
            TYPE VARCHAR;
        """)
    # ### end Alembic commands ###

    # ### end Alembic commands ###
