"""Add banExplicitLyrics and remove deprecated properties

Revision ID: ec8a44998f55
Revises: 23e927725060
Create Date: 2025-07-23 16:01:46.297403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8a44998f55'
down_revision = '23e927725060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banExplicitLyrics', sa.Boolean(), nullable=True))
        batch_op.drop_column('max_duration')
        batch_op.drop_column('min_duration')
        batch_op.drop_column('max_energy')
        batch_op.drop_column('min_acousticness')
        batch_op.drop_column('min_danceability')
        batch_op.drop_column('min_popularity')
        batch_op.drop_column('min_energy')
        batch_op.drop_column('max_danceability')
        batch_op.drop_column('max_acousticness')
        batch_op.drop_column('max_popularity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_popularity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_acousticness', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_danceability', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('min_energy', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('min_popularity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('min_danceability', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('min_acousticness', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_energy', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('min_duration', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_duration', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('banExplicitLyrics')

    # ### end Alembic commands ###
